version: '3.8'

services:
  # ------------------------
  # PostgreSQL Master
  # ------------------------
  postgres-master:
    image: postgres:15
    container_name: pg-master
    restart: always
    environment:
      POSTGRES_USER: otus
      POSTGRES_PASSWORD: otus_pass
      POSTGRES_DB: social_network
      # Включаем WAL streaming
      POSTGRES_INITDB_ARGS: "--wal-level=replica --max_wal_senders=5 --wal_keep_size=64"
    volumes:
      - ./postgres/master/data:/var/lib/postgresql/data
      - ./postgres/master/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/master/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  # ------------------------
  # PostgreSQL Slave 1
  # ------------------------
  postgres-slave1:
    image: postgres:15
    container_name: pg-slave1
    restart: always
    depends_on:
      - postgres-master
    environment:
      POSTGRES_USER: otus
      POSTGRES_PASSWORD: otus_pass
    volumes:
      - ./postgres/slave1/data:/var/lib/postgresql/data
      - ./postgres/slave1/recovery.conf:/var/lib/postgresql/data/recovery.conf
    ports:
      - "5433:5432"

  # ------------------------
  # PostgreSQL Slave 2
  # ------------------------
  postgres-slave2:
    image: postgres:15
    container_name: pg-slave2
    restart: always
    depends_on:
      - postgres-master
    environment:
      POSTGRES_USER: otus
      POSTGRES_PASSWORD: otus_pass
    volumes:
      - ./postgres/slave2/data:/var/lib/postgresql/data
      - ./postgres/slave2/recovery.conf:/var/lib/postgresql/data/recovery.conf
    ports:
      - "5434:5432"

  # ------------------------
  # PostgreSQL Exporter for Prometheus
  # ------------------------
  pg-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    container_name: pg-exporter
    restart: always
    environment:
      DATA_SOURCE_NAME: "postgresql://otus:otus_pass@postgres-master:5432/social_network?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - postgres-master

  # ------------------------
  # Prometheus
  # ------------------------
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - pg-exporter

  # ------------------------
  # Grafana
  # ------------------------
  grafana:
    image: grafana/grafana:9.0.0
    container_name: grafana
    restart: always
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
