version: '3.8'
networks:
  appnet:
    driver: bridge

x-common-env: &common-env
  POSTGRES_USER: coord
  POSTGRES_PASSWORD: coord
  POSTGRES_DB: socialdb_coord

services:
  # Worker nodes
  worker1:
    image: citusdata/citus:11.2
    environment:
      <<: *common-env
      COORDINATOR_HOST: coordinator
    ports:
      - "5433:5432"
    volumes:
      - ./postgres/sharding/init-workers.sql:/docker-entrypoint-initdb.d/init-workers.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "socialdb_coord" ]
      interval: 5s
      retries: 20
    networks:
      - appnet
    command:
      - postgres
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=32"
      - "-c"
      - "max_replication_slots=32"
      - "-c"
      - "shared_preload_libraries=citus"

  worker2:
    image: citusdata/citus:11.2
    environment:
      <<: *common-env
      COORDINATOR_HOST: coordinator
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "socialdb_coord" ]
      interval: 5s
      retries: 20
    volumes:
      - ./postgres/sharding/init-workers.sql:/docker-entrypoint-initdb.d/init-workers.sql
    ports:
      - "5434:5432"
    networks:
      - appnet
    command:
      - postgres
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=32"
      - "-c"
      - "max_replication_slots=32"
      - "-c"
      - "shared_preload_libraries=citus"
  # Coordinator
  coordinator:
    image: citusdata/citus:11.2
    ports:
      - "5432:5432"
    environment:
      <<: *common-env
      CITUS_WORKERS: "worker1:5432,worker2:5432"
      CITUS_NODE_NAME: coordinator
      CITUS_COORDINATOR_HOST: coordinator
    volumes:
      - ./postgres/sharding/init-citus.sql:/docker-entrypoint-initdb.d/init-citus.sql
      - ./postgres/sharding/init-workers.sql:/docker-entrypoint-initdb.d/init-workers.sql
    depends_on:
      worker1:
        condition: service_healthy
      worker2:
        condition: service_healthy
    networks:
      - appnet
    command:
      - postgres
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=32"
      - "-c"
      - "max_replication_slots=32"
      - "-c"
      - "shared_preload_libraries=citus"
  app:
    build: .
    container_name: social-app-sharded
    environment:
      SPRING_DATASOURCE_MASTER_URL: jdbc:postgresql://coordinator:5432/socialdb_coord
      SPRING_DATASOURCE_MASTER_USERNAME: coord
      SPRING_DATASOURCE_MASTER_PASSWORD: coord
      SPRING_DATASOURCE_SLAVE_URL: jdbc:postgresql://coordinator:5432/socialdb_coord
      SPRING_DATASOURCE_SLAVE_USERNAME: coord
      SPRING_DATASOURCE_SLAVE_PASSWORD: coord
      SPRING_PROFILES_ACTIVE: single
    ports:
      - "8080:8080"
    depends_on:
      - coordinator
    networks:
      - appnet
    command: ["sh", "-c", "./wait-for-it.sh coordinator:5432 -- java -jar app.jar"]