spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/socialdb
    username: socialuser
    password: socialpass
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
server:
  port: 8080
