spring:
  datasource:
    master:
      url: jdbc:postgresql://postgres-master:5432/social_network_rep
      username: otus
      password: otus_pass
      driver-class-name: org.postgresql.Driver
    slave:
      url: >-
        jdbc:postgresql://postgres-slave1:5432,postgres-slave2:5432/social_network_rep
        ?targetServerType=slave&loadBalanceHosts=true
      username: otus
      password: otus_pass
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

server:
  port: 8080

security:
  user:
    name: dummy     # later disable the default user
    password: dummy

jwt:
  secret: verySecretKeyReallySecretISwearYou
  access-token-validity-seconds: 900    # 15 minutes
  refresh-token-validity-seconds: 604800  # 7 days
