spring:
datasource:
  master:
    url: jdbc:postgresql://postgres-master:5432/social_network
    username: otus
    password: otus_pass
  slave:
    url: jdbc:postgresql://postgres-slave1:5432,postgres-slave2:5432/social_network?targetServerType=slave&loadBalanceHosts=true
    username: otus
    password: otus_pass
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
server:
  port: 8080
security:
  user:
    name: dummy     # отключим default-user позже
    password: dummy

jwt:
  secret: verySecretKeyReallySecretISwearYou
  access-token-validity-seconds: 900    # 15 минут
  refresh-token-validity-seconds: 604800  # 7 дней

