global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['pg-exporter:9187']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
