FROM postgres:15

# Переменные окружения
ENV POSTGRES_DB=socialdb
ENV POSTGRES_USER=socialuser
ENV POSTGRES_PASSWORD=socialpass


# COPY ./docker/initdb/*.sql /docker-entrypoint-initdb.d/

# Открываем порт
EXPOSE 5432

